# Generated by Django 5.1.3 on 2024-11-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancymodel',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='Горячая вакансия'),
        ),
    ]
