# Generated by Django 5.1.3 on 2024-11-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_advisor_employer_personaluser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(choices=[('almaty', 'Алматы'), ('nur-sultan', 'Нур-Султан'), ('shymkent', 'Шымкент'), ('karaganda', 'Караганда'), ('aktobe', 'Актобе'), ('taraz', 'Тараз'), ('pavlodar', 'Павлодар'), ('uralsk', 'Уральск'), ('ust-kamenogorsk', 'Усть-Каменогорск'), ('semey', 'Семей'), ('aktau', 'Актау'), ('atyrau', 'Атырау'), ('kostanay', 'Костанай'), ('kokshetau', 'Кокшетау'), ('petropavl', 'Петропавловск'), ('kyzylorda', 'Кызылорда')], default='astana', max_length=50),
        ),
        migrations.AddField(
            model_name='personaluser',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
