# Generated by Django 5.1.3 on 2024-11-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_customuser_city_personaluser_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaluser',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
